### ISSUE TITLE
ffscreencast --help gives error

### ISSUE THREAD

**Issue by strages** [cytopia/ffscreencast#7] opened 2016-02-01 13:05 UTC
It completely crashes my terminal. installed with the brew tap ;)

`ffscreencast --help`

**Comment by cytopia** [comment] 2016-02-01 13:21
What is `ffscreencast --test` saying?

**Comment by cytopia** [comment] 2016-02-01 13:58
Also please submit `ffmpeg --help`.

**Comment by strages** [comment] 2016-02-01 15:09
ffscreencast --test outputs the following after quitting the terminal:

[OK]   Operating system supported: Darwin
[OK]   ffmpeg found: /usr/local/bin/ffmpeg
[OK]   [OSX]: AVFoundation available in ffmpeg.
          + Desktop recording possible.
          + Sound recording possible.
          + Camera overlay possible.

ffmpeg --help

seems to work fine

On Mon, Feb 1, 2016 at 2:58 PM cytopia <notifications@github.com> wrote:

> Also please submit ffmpeg --help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cytopia/ffscreencast/issues/7#issuecomment-177983046>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by cytopia** [comment] 2016-02-01 15:15
This is really strange. `ffscreencast --help` mostly only runs `echo` and `printf` commands.

Could you try again and see how far you can get (knowing that it might crash).


```shell
bash -x /usr/local/bin/ffscreencast --help
```
> `bash -x` turns on debugging and shows all called lines from the script.

Also could you try another terminal app and see if it behaves the same. (I have tried iTerm and Terminal so far)

**Comment by cytopia** [comment] 2016-03-31 06:37
I am closing this as no one seems to be able to reproduce this error.
If this is still an active issue for you, please submit the above `-x` output

**Comment by strages** [comment] 2016-03-31 07:10
sorry i forgot about this completely

it gives me the following output on iterm (running latest version):

```
❯ bash -x /usr/local/bin/ffscreencast --help
+ INFO_AUTHOR='Patrick Plocke <patrick@plocke.de>'
+ INFO_GPGKEY=0x28BF179F
+ INFO_DATE=2015-12-21
+ INFO_LICENSE=MIT
+ INFO_VERSION=0.6
+ INFO_NAME=ffscreencast
++ date +%Y-%m-%d
+ DATE=2016-03-31
++ date +%H.%M.%S
+ TIME=09.06.56
+ NAME='Screencast 2016-03-31 at 09.06.56'
+ DIR=/Users/Dimitrie/Desktop
+ OUTPUT_EXT=mkv
+ OUTPUT_ACODEC=libfaac
+ OUTPUT_VCODEC=libx264
+ S_ARGS=
+ A_ARGS='-ac 2'
+ C_ARGS=
+ O_ARGS='-crf 0 -preset ultrafast'
+ RECORD_S=yes
+ RECORD_A=no
+ RECORD_C=no
+ CHOSEN_S_NUM=
+ CHOSEN_A_NUM=
+ CHOSEN_C_NUM=
++ which grep
+ GREP=/usr/bin/grep
++ which awk
+ AWK=/usr/local/bin/awk
++ which sed
+ SED=/usr/bin/sed
++ which ffmpeg
+ FFMPEG=/usr/local/bin/ffmpeg
++ uname
+ UNAME=Darwin
+ EXIT_ERR=1
+ EXIT_OK=0
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ print_help
+ print_usage
+ printf '%s %s %s\n' Usage: ffscreencast '[-s[num]] [--sargs=] [-a[num]] [--aargs=] [-c[num] [--cargs=] [--oargs=] [-e<ext>] [--dry]'
Usage: ffscreencast [-s[num]] [--sargs=] [-a[num]] [--aargs=] [-c[num] [--cargs=] [--oargs=] [-e<ext>] [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast '--slist [--dry]'
       ffscreencast --slist [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast '--alist [--dry]'
       ffscreencast --alist [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast '--clist [--dry]'
       ffscreencast --clist [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast --help
       ffscreencast --help
+ printf '%s %s %s\n' '      ' ffscreencast --version
       ffscreencast --version
+ printf '%s %s %s\n' '      ' ffscreencast --test
       ffscreencast --test
+ echo

+ echo 'When invoked without any arguments, it will start screen recording'
When invoked without any arguments, it will start screen recording
+ echo 'on the default screen without sound and without camera overlay.'
on the default screen without sound and without camera overlay.
+ echo

+ echo 'Input options:'
Input options:
+ echo '-s[num]           (Default) Enable screen capturing [with device number X].'
-s[num]           (Default) Enable screen capturing [with device number X].
+ echo '                  If no device number is specified it will use the default, if only'
                  If no device number is specified it will use the default, if only
+ echo '                  one device is present, otherwise it will ask you to choose one'
                  one device is present, otherwise it will ask you to choose one
+ echo '                  Use: -s or -s1'
                  Use: -s or -s1
+ echo

+ echo '--sargs=          Additional screen arguments.'
--sargs=          Additional screen arguments.
+ echo '                  Specify additional ffmpeg arguments for the screen input device.'
                  Specify additional ffmpeg arguments for the screen input device.
+ echo '                  Use: --sargs="-framerate 30"'
                  Use: --sargs="-framerate 30"
+ echo '                  Default: '\'''\'''
                  Default: ''
+ echo

+ echo '-a[num]           Enable audio capturing [with device number X]'
-a[num]           Enable audio capturing [with device number X]
+ echo '                  If no device number is specified it will use the default, if only'
                  If no device number is specified it will use the default, if only
+ echo '                  one device is present, otherwise it will ask you to choose one'
                  one device is present, otherwise it will ask you to choose one
+ echo '                  Use: -a or -a1'
                  Use: -a or -a1
+ echo

+ echo '--aargs=          Additional audio arguments.'
--aargs=          Additional audio arguments.
+ echo '                  Specify additional ffmpeg arguments for the audio input device.'
                  Specify additional ffmpeg arguments for the audio input device.
+ echo '                  Use: --aargs="-ac 1"'
                  Use: --aargs="-ac 1"
+ echo '                  Default: '\''-ac 2'\'''
                  Default: '-ac 2'
+ echo

+ echo '-c[num]           Add camera overlay [with device number X]'
-c[num]           Add camera overlay [with device number X]
+ echo '                  If no device number is specified it will use the default, if only'
                  If no device number is specified it will use the default, if only
+ echo '                  one device is present, otherwise it will ask you to choose one'
                  one device is present, otherwise it will ask you to choose one
+ echo '                  Use: -c or -c1'
                  Use: -c or -c1
+ echo

+ echo '--cargs=          Additional camera arguments'
--cargs=          Additional camera arguments
+ echo '                  Specify additional ffmpeg arguments for the camera input device.'
                  Specify additional ffmpeg arguments for the camera input device.
+ echo '                  Use: --cargs="-video_size 1280x720"'
                  Use: --cargs="-video_size 1280x720"
+ echo '                  Default: '\'''\'''
                  Default: ''
+ echo

+ echo

+ echo 'Output options:'
Output options:
+ echo '-e<ext>           Output video format extension (Default: mkv)'
-e<ext>           Output video format extension (Default: mkv)
+ echo '                  E.g.: -emkv, or -eavi, or -emp4'
                  E.g.: -emkv, or -eavi, or -emp4
+ echo

+ echo '-oargs=           Additional output arguments'
-oargs=           Additional output arguments
+ echo '                  Specify additional ffmpeg arguments for the output encoding.'
                  Specify additional ffmpeg arguments for the output encoding.
+ echo '                  Use: --oargs="-crf 0"'
                  Use: --oargs="-crf 0"
+ echo '                  Default: '\''-crf 0 -preset ultrafast'\'''
                  Default: '-crf 0 -preset ultrafast'
+ echo

+ echo

+ echo 'Behavior options:'
Behavior options:
+ echo '--dry             Show the command (without executing)'
--dry             Show the command (without executing)
+ echo

+ echo

+ echo 'List options:'
List options:
+ echo '--list            List all devices'
--list            List all devices
+ echo '--slist           Only list screen capturing devices (monitors)'
--slist           Only list screen capturing devices (monitors)
+ echo '--alist           Only list audio capturing devices (microphones)'
--alist           Only list audio capturing devices (microphones)
+ echo '--clist           Only list camera capturing devices (cams)'
--clist           Only list camera capturing devices (cams)
+ echo

+ echo

+ echo 'System information:'
System information:
+ echo '--help            Show this help screen'
--help            Show this help screen
+ echo '--version         Show version information'
--version         Show version information
+ echo '--test            Test requirements'
--test            Test requirements
+ exit 0
```
same output i believe on native terminal of osx

```
bash -x /usr/local/bin/ffscreencast --help
+ INFO_AUTHOR='Patrick Plocke <patrick@plocke.de>'
+ INFO_GPGKEY=0x28BF179F
+ INFO_DATE=2015-12-21
+ INFO_LICENSE=MIT
+ INFO_VERSION=0.6
+ INFO_NAME=ffscreencast
++ date +%Y-%m-%d
+ DATE=2016-03-31
++ date +%H.%M.%S
+ TIME=09.07.33
+ NAME='Screencast 2016-03-31 at 09.07.33'
+ DIR=/Users/Dimitrie/Desktop
+ OUTPUT_EXT=mkv
+ OUTPUT_ACODEC=libfaac
+ OUTPUT_VCODEC=libx264
+ S_ARGS=
+ A_ARGS='-ac 2'
+ C_ARGS=
+ O_ARGS='-crf 0 -preset ultrafast'
+ RECORD_S=yes
+ RECORD_A=no
+ RECORD_C=no
+ CHOSEN_S_NUM=
+ CHOSEN_A_NUM=
+ CHOSEN_C_NUM=
++ which grep
+ GREP=/usr/bin/grep
++ which awk
+ AWK=/usr/local/bin/awk
++ which sed
+ SED=/usr/bin/sed
++ which ffmpeg
+ FFMPEG=/usr/local/bin/ffmpeg
++ uname
+ UNAME=Darwin
+ EXIT_ERR=1
+ EXIT_OK=0
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ print_help
+ print_usage
+ printf '%s %s %s\n' Usage: ffscreencast '[-s[num]] [--sargs=] [-a[num]] [--aargs=] [-c[num] [--cargs=] [--oargs=] [-e<ext>] [--dry]'
Usage: ffscreencast [-s[num]] [--sargs=] [-a[num]] [--aargs=] [-c[num] [--cargs=] [--oargs=] [-e<ext>] [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast '--slist [--dry]'
       ffscreencast --slist [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast '--alist [--dry]'
       ffscreencast --alist [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast '--clist [--dry]'
       ffscreencast --clist [--dry]
+ printf '%s %s %s\n' '      ' ffscreencast --help
       ffscreencast --help
+ printf '%s %s %s\n' '      ' ffscreencast --version
       ffscreencast --version
+ printf '%s %s %s\n' '      ' ffscreencast --test
       ffscreencast --test
+ echo

+ echo 'When invoked without any arguments, it will start screen recording'
When invoked without any arguments, it will start screen recording
+ echo 'on the default screen without sound and without camera overlay.'
on the default screen without sound and without camera overlay.
+ echo

+ echo 'Input options:'
Input options:
+ echo '-s[num]           (Default) Enable screen capturing [with device number X].'
-s[num]           (Default) Enable screen capturing [with device number X].
+ echo '                  If no device number is specified it will use the default, if only'
                  If no device number is specified it will use the default, if only
+ echo '                  one device is present, otherwise it will ask you to choose one'
                  one device is present, otherwise it will ask you to choose one
+ echo '                  Use: -s or -s1'
                  Use: -s or -s1
+ echo

+ echo '--sargs=          Additional screen arguments.'
--sargs=          Additional screen arguments.
+ echo '                  Specify additional ffmpeg arguments for the screen input device.'
                  Specify additional ffmpeg arguments for the screen input device.
+ echo '                  Use: --sargs="-framerate 30"'
                  Use: --sargs="-framerate 30"
+ echo '                  Default: '\'''\'''
                  Default: ''
+ echo

+ echo '-a[num]           Enable audio capturing [with device number X]'
-a[num]           Enable audio capturing [with device number X]
+ echo '                  If no device number is specified it will use the default, if only'
                  If no device number is specified it will use the default, if only
+ echo '                  one device is present, otherwise it will ask you to choose one'
                  one device is present, otherwise it will ask you to choose one
+ echo '                  Use: -a or -a1'
                  Use: -a or -a1
+ echo

+ echo '--aargs=          Additional audio arguments.'
--aargs=          Additional audio arguments.
+ echo '                  Specify additional ffmpeg arguments for the audio input device.'
                  Specify additional ffmpeg arguments for the audio input device.
+ echo '                  Use: --aargs="-ac 1"'
                  Use: --aargs="-ac 1"
+ echo '                  Default: '\''-ac 2'\'''
                  Default: '-ac 2'
+ echo

+ echo '-c[num]           Add camera overlay [with device number X]'
-c[num]           Add camera overlay [with device number X]
+ echo '                  If no device number is specified it will use the default, if only'
                  If no device number is specified it will use the default, if only
+ echo '                  one device is present, otherwise it will ask you to choose one'
                  one device is present, otherwise it will ask you to choose one
+ echo '                  Use: -c or -c1'
                  Use: -c or -c1
+ echo

+ echo '--cargs=          Additional camera arguments'
--cargs=          Additional camera arguments
+ echo '                  Specify additional ffmpeg arguments for the camera input device.'
                  Specify additional ffmpeg arguments for the camera input device.
+ echo '                  Use: --cargs="-video_size 1280x720"'
                  Use: --cargs="-video_size 1280x720"
+ echo '                  Default: '\'''\'''
                  Default: ''
+ echo

+ echo

+ echo 'Output options:'
Output options:
+ echo '-e<ext>           Output video format extension (Default: mkv)'
-e<ext>           Output video format extension (Default: mkv)
+ echo '                  E.g.: -emkv, or -eavi, or -emp4'
                  E.g.: -emkv, or -eavi, or -emp4
+ echo

+ echo '-oargs=           Additional output arguments'
-oargs=           Additional output arguments
+ echo '                  Specify additional ffmpeg arguments for the output encoding.'
                  Specify additional ffmpeg arguments for the output encoding.
+ echo '                  Use: --oargs="-crf 0"'
                  Use: --oargs="-crf 0"
+ echo '                  Default: '\''-crf 0 -preset ultrafast'\'''
                  Default: '-crf 0 -preset ultrafast'
+ echo

+ echo

+ echo 'Behavior options:'
Behavior options:
+ echo '--dry             Show the command (without executing)'
--dry             Show the command (without executing)
+ echo

+ echo

+ echo 'List options:'
List options:
+ echo '--list            List all devices'
--list            List all devices
+ echo '--slist           Only list screen capturing devices (monitors)'
--slist           Only list screen capturing devices (monitors)
+ echo '--alist           Only list audio capturing devices (microphones)'
--alist           Only list audio capturing devices (microphones)
+ echo '--clist           Only list camera capturing devices (cams)'
--clist           Only list camera capturing devices (cams)
+ echo

+ echo

+ echo 'System information:'
System information:
+ echo '--help            Show this help screen'
--help            Show this help screen
+ echo '--version         Show version information'
--version         Show version information
+ echo '--test            Test requirements'
--test            Test requirements
+ exit 0
```

**Comment by cytopia** [comment] 2016-03-31 07:12
Does it still freeze your terminal or did you identify something else for that issue?

**Comment by strages** [comment] 2016-03-31 09:07
it just closes it...

On Thu, Mar 31, 2016 at 9:12 AM cytopia <notifications@github.com> wrote:

> Does it still freeze your terminal or did you identify something else for
> that issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cytopia/ffscreencast/issues/7#issuecomment-203791592>
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by cytopia** [comment] 2016-04-02 11:48
Maybe there is some misunderstanding between us:

Your main complain is: `ffscreencast --help gives error`

But I also see this comment from you
> ffmpeg --help
> 
> seems to work fine

Also this one:
> ffscreencast --test outputs the following after quitting the terminal:
> ...

I don't quite get this. It shows output after ther terminal is closed?

> it just closes it...


So just to be on the same line: Your terminal program (iterm or Terminal.app) is automatically close by `ffscreencast` when you use it with `--help`

Is this correct?

If so, is it closed before or after you see the output?

**Comment by strages** [comment] 2016-04-02 20:19
that is correct! 

I type in the command and the following happens...

to prove it, here is a little screencast:

![ffscreencasthelp](https://cloud.githubusercontent.com/assets/429659/14228804/cb5fb0e6-f920-11e5-8f23-2218f111eb77.gif)

**Comment by cytopia** [comment] 2016-04-03 08:26
Hi @strages,

thanks for the screencast, it made it clearer.

I guess this is a configuration issue with your terminal.

I found this:

https://stackoverflow.com/questions/8798641/close-terminal-window-from-within-shell-script-unix

and this

https://apple.stackexchange.com/questions/134561/command-to-close-terminal-window

Can you double check if your terminal is set to close on clean exit

**Comment by strages** [comment] 2016-04-03 09:06
this is my setting in terminal app 

![image](https://cloud.githubusercontent.com/assets/429659/14231647/87a23160-f98b-11e5-9ec8-b2a6c28c5f78.png)

`exit 0` gives therefore 

![image](https://cloud.githubusercontent.com/assets/429659/14231651/a33ce6f4-f98b-11e5-849a-fc5c23090c07.png)


however when using iterm, it does close immidiately when `exit 0`

it has this setting:

![image](https://cloud.githubusercontent.com/assets/429659/14231666/034f42c6-f98c-11e5-92cf-3c291a7031a2.png)

thanks for the help btw

**Comment by cytopia** [comment] 2016-04-03 09:10
You can also test it with simple scripts in your terminals

All these should NOT exit the terminal
```shell
#!/usr/bin/env bash
echo "env bash test"
exit 0
```

```shell
#!/bin/bash
echo "bash test"
exit 0
```

```shell
#!/bin/sh
echo "sh test"
exit 0
```

**Comment by strages** [comment] 2016-04-03 09:19
they do not exit my terminal ;)

![image](https://cloud.githubusercontent.com/assets/429659/14231726/ed8e8d46-f98d-11e5-8324-9a7d42e79ea0.png)

**Comment by cytopia** [comment] 2016-04-03 09:56
Hmm, the only other thing I could imagine is some interference with your bash/zsh (or the shell you are using) configuration.

Could you try to use a non-configured shell. For example `tcsh`

```shell
brew install tcsh
tsch
./ffscreencast --help
```

**Comment by strages** [comment] 2016-04-03 20:03
then it works :)

**Comment by cytopia** [comment] 2016-04-04 06:34
OK, then we finally found the problem for it.

I would suggest turning off the .zsh ( or bash) config an enabling it peace by peace to see what is causing the exit.

In case it is actualy oh-my-zsh, you will probably need to open up a ticket over there.

I will close this ticket then as there is nothing I can do about.

**Closed by cytopia** 2016-04-04 06:34 UTC
Labels: invalid
